name: Showcase
markdown: kramdown
plugins:
  - jekyll-coffeescript
exclude:
  - _scripts
  - _coffee
  - _junk
  - node_modules
  - package.json
  - CNAME
  - README.md
  - _data/Readme.md
  - _sass/Readme.md
